export const PRODUCT = {
  LOAD: "REQUEST_PRODUCT_DATA",
  LOAD_SUCCESS: "RECEIVE_PRODUCT_DATA",
  SEARCH: "SEARCH_PRODUCT"
}

export const CATEGORY = {
  LOAD: "REQUEST_CATEGORY_DATA",
  LOAD_CATEGORY_SUCCESS: "RECEIVE_CATEGORY_DATA",
}

export const CART = {
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  UPDATE_QTY_CART: "UPDATE_QTY_CART"
}

export const LISTNAME = {
  LOAD: "REQUEST_LISTNAME_DATA",
  LOAD_SUCCESS: "RECEIVE_LISTNAME_DATA",
}

export const USER = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',
}

